sudo: false
language: node_js
node_js: 
  - "9"
script:
  - npm run lint
  - npm test
  - npm run build
deploy:
  provider: heroku
  app: bc-mail
  api_key: 
    secure: "e92dba93-f6a1-4aca-8f09-f1e0db331c56"
